### ISSUE TITLE
Prototype 1D moving content to body

### ISSUE THREAD

**Issue by alvarezguille** [vaadin/vaadin-login#26]
The idea is to move content of shadow root to light dom so that it's accessible by browser autocomplete and password managers.
One option could be with vaadin-overlay.
We can prototype this just using `input` element

**Comment by DiegoCardoso** [comment]
**WIP** can be found here: https://github.com/vaadin/vaadin-login/tree/prototype/%2326-move-content-body

#### Findings:
`vaadin-overlay` was used in order to make it add the elements in the root level no matter where the `vaadin-login` component is attached. 
Then, the current `vaadin-login` markup was moved into the `vaadin-overlay` shadow DOM by defining it within a `template` tag.
Added a `slot`, so the username/password input (switched from `vaadin-text-field`/`vaadin-password-field` to plain HTML `input`s) could go to the light DOM, hence making it be reachable by password managers.

It was possible to make password managers (LastPass and 1Password) work.

#### What needs to be fixed/improved:

1. Possibility to add named slots which would make it easier to integrate with slotted `vaadin-text-field`
	1.1. Named slot only worked if element is added to `this.$.overlay.$.content` which makes it go to `content`'s shadow DOM
2. Currently it doesn't work with ShadyDOM (inputs get lost)
	2.1. Because of that, tests on the inputs are failing
3. It wasn't able to fill the login form using LastPass popup, only through plugin's icon at toolbar (it looks like some issue with the backdrop)
4. Investigate how to improve the usage of `vaadin-overlay`

PS. Changed the demo just to make easier to see it working.

**Comment by alvarezguille** [comment]
Next step 1 D prototyping using https://github.com/vaadin/vaadin-text-field/tree/proto/slotted-input
