### ISSUE TITLE
Add support to password managers

### ISSUE THREAD

**Issue by DiegoCardoso** [vaadin/vaadin-login#8]
The username/password should be able to work with a password manager (eg. 1Password and LastPass)

**Comment by jojule** [comment]
Looks password managers work in the full-screen demo, but not in the default demo. See the attached video. 

![1pwd](https://user-images.githubusercontent.com/644969/50717146-3253a180-103a-11e9-8444-08759d2eeacc.gif)

**Comment by alexberazouski** [comment]
@jojule 
To make `vaadin-login` work with password managers all the inputs should be directly accessible from a document layer. `login-overlay` provides this functionality, since it always attaches itself to a document root and also exposes inputs:
https://github.com/vaadin/vaadin-login/blob/303c021e301a1bade01aca9fdecca6a295d77439/src/vaadin-login-overlay.html#L34..L56

Unfortunately, in case of the demo, `vaadin-login` is hidden under number of demo helper elements.

**Comment by jojule** [comment]
I think we should find a workaround we could implement in the demo - now it demos that the login is broken. Someone evaluating this would not understand why.

**Comment by alvarezguille** [comment]
`vaadin-login-overlay` is the one with password manager support.
Using `vaadin-login` inline in another shadow root kills the feature and we should emphasize this on documentation and demo context if it's not clear yet.
 
Adding a workaround to the demo will confuse the user more once he tries the demo sources.

We will re-order the demos to have `vaadin-login-overlay` demos first (#76).
And add an advanced demo of how to provide the inputs "accessible from a document layer" when using the element inline.

WDYT @jojule?

**Comment by tulioag** [comment]
This issue was addressed here: https://github.com/vaadin/vaadin-login/commit/6cd2413fc002d4c49b1b2a4bbad3e8531889827a

The following actions were taken:
* Removed `vaadin-login` since it doesn't provide password managers support and its name makes it look like the main component.
* Created an internal `vaadin-login-form-wrapper` for handling native forms.
* Created a new element, `vaadin-login-form`, which can be used inline and has password manager support as long as it's not inside a shadow root.
