### ISSUE TITLE
Forgot password button is not visible in bakery app

### ISSUE THREAD

**Issue by sudipta1411** [vaadin/vaadin-login#93]
Hi,
I am trying to learn the  JAVA framework. In the source code of vaadin bakery app, there is call to `setForgotPasswordButtonVisible(true);` in the constructor of LoginView.java. But no forgot password button is shown in the app.

**Comment by DiegoCardoso** [comment]
Hello @sudipta1411,

If you take a look to the code before the call you mentioned, there's one `i18n.setForm(new LoginI18n.Form());`, which basically creates an empty object and that's why no text is being set to the `i18n.form.forgotPassword` property, therefore causing it to show empty on the page (you can even inspect that the button is present there).

You can either remove the line `i18n.setForm(new LoginI18n.Form());` or make a call to `i18n.getForm().setForgotPassword("button text");`.

**Comment by sudipta1411** [comment]
Ok. Thanks for replying. I have inspected that. I thought it was the default behaviour
